[tool.poetry]
name = "ai-assist-hacaton"
version = "0.1.0"
description = ""
authors = ["ivan_note <ivansyn2013@yandex.ru>"]
readme = "README.md"
packages = [{include = "ai_assist_hacaton"}]

[tool.poetry.dependencies]
python = "^3.11"
tqdl = "^0.0.4"
openai = "^2.4.0"
fastapi = "^0.119.0"
loguru = "^0.7.3"
uvicorn = "^0.37.0"
python-dotenv = "^1.1.1"
yandex-cloud-ml-sdk = "^0.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
